#!/usr/bin/env python3
"""
Social Summary Skill - AI Employee

Tracks and summarizes social media activities:
- Logs LinkedIn posts and other social media
- Saves to Reports/Social_Log.md
- Generates platform summaries
- Tracks engagement metrics

Usage:
    python social_summary.py log --platform linkedin --content "Post text"
    python social_summary.py summary [--days 7]
    python social_summary.py recent [--limit 10]
    python social_summary.py export --format json

Environment:
    VAULT_ROOT: Path to AI_Employee_Vault (default: parent of scripts directory)
"""

import os
import sys
import json
import argparse
from datetime import datetime, timedelta
from pathlib import Path
from typing import Dict, List, Optional


# ============================================================================
# Configuration
# ============================================================================

class Config:
    """Configuration for social summary manager."""
    
    # Always use parent directory of this script as vault root
    VAULT_ROOT = Path(__file__).resolve().parent.parent
    
    REPORTS_DIR = VAULT_ROOT / "Reports"
    LOGS_DIR = VAULT_ROOT / "Logs"
    SOCIAL_LOG = REPORTS_DIR / "Social_Log.md"
    SOCIAL_JSON_LOG = LOGS_DIR / "social_activity.json"
    
    # Ensure directories exist
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    LOGS_DIR.mkdir(parents=True, exist_ok=True)


# ============================================================================
# Social Summary Manager
# ============================================================================

class SocialSummaryManager:
    """Manages social media activity logging and summaries."""
    
    def __init__(self, vault_root: Path = None):
        """Initialize social summary manager."""
        self.vault_root = vault_root or Config.VAULT_ROOT
        
        # Define paths
        self.reports_dir = Config.REPORTS_DIR
        self.social_log = Config.SOCIAL_LOG
        self.logs_dir = Config.LOGS_DIR
        self.social_json_log = Config.SOCIAL_JSON_LOG
        
        # Initialize social log if doesn't exist
        if not self.social_log.exists():
            self._initialize_social_log()
    
    def _initialize_social_log(self):
        """Initialize Social_Log.md with header."""
        header = f"""# Social Media Activity Log

**Last Updated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

---

## Recent Activity

| Date | Platform | Content | Status | Engagement |
|------|----------|---------|--------|------------|

---

## Platform Summary

| Platform | Total Posts | Avg Likes | Avg Comments | Last Post |
|----------|-------------|-----------|--------------|-----------|

---

## Content Log

---

*Generated by social-summary skill*
"""
        with open(self.social_log, 'w', encoding='utf-8') as f:
            f.write(header)
    
    def _load_activities(self) -> List[Dict]:
        """Load existing activities from JSON log."""
        if not self.social_json_log.exists():
            return []
        
        try:
            with open(self.social_json_log, 'r', encoding='utf-8') as f:
                return json.load(f)
        except Exception:
            return []
    
    def _save_activities(self, activities: List[Dict]):
        """Save activities to JSON log."""
        with open(self.social_json_log, 'w', encoding='utf-8') as f:
            json.dump(activities, f, indent=2, default=str)
    
    def log_post(self, platform: str, content: str, post_id: str = None,
                post_url: str = None, status: str = "published",
                engagement: Dict = None, tags: List[str] = None) -> Dict:
        """
        Log a social media post.
        
        Args:
            platform: Social media platform
            content: Post content
            post_id: Platform-specific post ID
            post_url: Direct URL to post
            status: Post status (published/scheduled/draft/failed)
            engagement: Engagement metrics dict
            tags: List of hashtags/tags
        
        Returns:
            Dict with logging result
        """
        timestamp = datetime.now()
        
        # Create activity record
        activity = {
            "timestamp": timestamp.isoformat(),
            "date": timestamp.strftime('%Y-%m-%d'),
            "platform": platform.lower(),
            "content": content[:500] + '...' if len(content) > 500 else content,
            "full_content": content,
            "post_id": post_id,
            "post_url": post_url,
            "status": status,
            "engagement": engagement or {},
            "tags": tags or [],
            "logged_at": timestamp.strftime('%Y-%m-%d %H:%M:%S')
        }
        
        # Load existing activities
        activities = self._load_activities()
        
        # Add new activity
        activities.append(activity)
        
        # Save to JSON log
        self._save_activities(activities)
        
        # Update markdown log
        self._update_markdown_log(activities)
        
        return {
            "success": True,
            "message": f"Social activity logged: {platform}",
            "activity": {
                "platform": platform,
                "date": activity["date"],
                "status": status
            }
        }
    
    def _update_markdown_log(self, activities: List[Dict]):
        """Update the markdown Social_Log.md file."""
        # Sort activities by date (newest first)
        sorted_activities = sorted(activities, key=lambda x: x.get('timestamp', ''), reverse=True)
        
        # Generate recent activity table
        recent_rows = ""
        for activity in sorted_activities[:20]:
            date = activity.get('date', 'Unknown')
            platform = activity.get('platform', 'Unknown').title()
            content = activity.get('content', '')[:50] + '...' if len(activity.get('content', '')) > 50 else activity.get('content', '')
            status = activity.get('status', 'unknown')
            status_icon = "✅" if status == "published" else "⏳" if status == "scheduled" else "📝" if status == "draft" else "❌"
            
            # Format engagement
            engagement = activity.get('engagement', {})
            engagement_str = ""
            if engagement:
                parts = []
                if 'likes' in engagement:
                    parts.append(f"{engagement['likes']} likes")
                if 'comments' in engagement:
                    parts.append(f"{engagement['comments']} comments")
                if 'shares' in engagement:
                    parts.append(f"{engagement['shares']} shares")
                engagement_str = ", ".join(parts)
            
            recent_rows += f"| {date} | {platform} | {content} | {status_icon} {status.title()} | {engagement_str} |\n"
        
        # Generate platform summary
        platform_stats = {}
        for activity in sorted_activities:
            if activity.get('status') != 'published':
                continue
            
            platform = activity.get('platform', 'unknown')
            if platform not in platform_stats:
                platform_stats[platform] = {
                    "posts": 0,
                    "total_likes": 0,
                    "total_comments": 0,
                    "total_shares": 0,
                    "last_post": activity.get('date', 'Unknown')
                }
            
            platform_stats[platform]["posts"] += 1
            engagement = activity.get('engagement', {})
            platform_stats[platform]["total_likes"] += engagement.get('likes', 0)
            platform_stats[platform]["total_comments"] += engagement.get('comments', 0)
            platform_stats[platform]["total_shares"] += engagement.get('shares', 0)
            platform_stats[platform]["last_post"] = activity.get('date', 'Unknown')
        
        # Generate summary table
        summary_rows = ""
        for platform, stats in sorted(platform_stats.items()):
            avg_likes = stats["total_likes"] / stats["posts"] if stats["posts"] > 0 else 0
            avg_comments = stats["total_comments"] / stats["posts"] if stats["posts"] > 0 else 0
            summary_rows += f"| {platform.title()} | {stats['posts']} | {avg_likes:.1f} | {avg_comments:.1f} | {stats['last_post']} |\n"
        
        # Generate content log
        content_log = ""
        for activity in sorted_activities[:50]:
            if activity.get('status') != 'published':
                continue
            
            date = activity.get('date', 'Unknown')
            platform = activity.get('platform', 'Unknown').title()
            content = activity.get('full_content', activity.get('content', ''))
            post_id = activity.get('post_id', 'N/A')
            post_url = activity.get('post_url', 'N/A')
            tags = activity.get('tags', [])
            engagement = activity.get('engagement', {})
            
            content_log += f"\n### {date} - {platform}\n\n"
            if post_id != 'N/A':
                content_log += f"**Post ID:** {post_id}\n"
            if post_url != 'N/A':
                content_log += f"**URL:** {post_url}\n"
            content_log += f"**Content:**\n> {content}\n\n"
            
            if tags:
                content_log += f"**Hashtags:** {' '.join(tags)}\n\n"
            
            if engagement:
                content_log += "**Engagement:**\n"
                if 'likes' in engagement:
                    content_log += f"- Likes: {engagement['likes']}\n"
                if 'comments' in engagement:
                    content_log += f"- Comments: {engagement['comments']}\n"
                if 'shares' in engagement:
                    content_log += f"- Shares: {engagement['shares']}\n"
            
            content_log += "\n---\n"
        
        # Build complete log
        log_content = f"""# Social Media Activity Log

**Last Updated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

---

## Recent Activity

| Date | Platform | Content | Status | Engagement |
|------|----------|---------|--------|------------|
{recent_rows}
---

## Platform Summary

| Platform | Total Posts | Avg Likes | Avg Comments | Last Post |
|----------|-------------|-----------|--------------|-----------|
{summary_rows if summary_rows else '| - | - | - | - | - |'}
---

## Content Log
{content_log if content_log else '\n*No posts logged yet.*\n'}
*Generated by social-summary skill*
"""
        
        # Write to file
        with open(self.social_log, 'w', encoding='utf-8') as f:
            f.write(log_content)
    
    def get_summary(self, days: int = 7, platform: str = None) -> Dict:
        """Get social media summary."""
        cutoff = datetime.now() - timedelta(days=days)
        activities = self._load_activities()
        
        # Filter activities
        filtered = []
        for activity in activities:
            try:
                activity_date = datetime.fromisoformat(activity.get('timestamp', ''))
                if activity_date >= cutoff:
                    if platform is None or activity.get('platform', '').lower() == platform.lower():
                        filtered.append(activity)
            except Exception:
                continue
        
        # Calculate statistics
        stats = {
            "total_posts": len(filtered),
            "by_platform": {},
            "by_status": {},
            "total_engagement": {
                "likes": 0,
                "comments": 0,
                "shares": 0
            },
            "period_days": days
        }
        
        for activity in filtered:
            platform = activity.get('platform', 'unknown')
            status = activity.get('status', 'unknown')
            engagement = activity.get('engagement', {})
            
            # Count by platform
            stats["by_platform"][platform] = stats["by_platform"].get(platform, 0) + 1
            
            # Count by status
            stats["by_status"][status] = stats["by_status"].get(status, 0) + 1
            
            # Sum engagement
            stats["total_engagement"]["likes"] += engagement.get('likes', 0)
            stats["total_engagement"]["comments"] += engagement.get('comments', 0)
            stats["total_engagement"]["shares"] += engagement.get('shares', 0)
        
        return stats
    
    def get_recent_posts(self, limit: int = 10, platform: str = None) -> List[Dict]:
        """Get recent posts."""
        activities = self._load_activities()
        
        # Sort by timestamp (newest first)
        sorted_activities = sorted(activities, key=lambda x: x.get('timestamp', ''), reverse=True)
        
        # Filter by platform if specified
        if platform:
            sorted_activities = [a for a in sorted_activities if a.get('platform', '').lower() == platform.lower()]
        
        return sorted_activities[:limit]


# ============================================================================
# CLI Functions
# ============================================================================

def cmd_log(args, manager: SocialSummaryManager):
    """Log a social media post."""
    # Parse engagement if provided
    engagement = None
    if hasattr(args, 'engagement') and args.engagement:
        try:
            engagement = json.loads(args.engagement)
        except Exception as e:
            print(f"[WARNING] Could not parse engagement JSON: {e}")
    
    # Parse tags if provided
    tags = None
    if hasattr(args, 'tags') and args.tags:
        tags = [t.strip() for t in args.tags.split(',')]
    
    result = manager.log_post(
        platform=args.platform,
        content=args.content,
        post_id=args.post_id if hasattr(args, 'post_id') else None,
        post_url=args.post_url if hasattr(args, 'post_url') else None,
        status=args.status if hasattr(args, 'status') else 'published',
        engagement=engagement,
        tags=tags
    )
    
    print(f"\n[OK] {result['message']}")
    print(f"     Platform: {result['activity']['platform']}")
    print(f"     Date: {result['activity']['date']}")
    print(f"     Status: {result['activity']['status']}")
    print(f"\n[INFO] Log saved to: {manager.social_log}")


def cmd_summary(args, manager: SocialSummaryManager):
    """Show social media summary."""
    stats = manager.get_summary(
        days=args.days if hasattr(args, 'days') else 7,
        platform=args.platform if hasattr(args, 'platform') else None
    )
    
    print(f"\n{'='*60}")
    print(f"Social Media Summary (Last {stats['period_days']} days)")
    print(f"{'='*60}")
    print(f"\nTotal Posts: {stats['total_posts']}")
    
    if stats['by_platform']:
        print(f"\nBy Platform:")
        for platform, count in sorted(stats['by_platform'].items(), key=lambda x: x[1], reverse=True):
            print(f"  {platform.title()}: {count}")
    
    if stats['by_status']:
        print(f"\nBy Status:")
        for status, count in stats['by_status'].items():
            print(f"  {status.title()}: {count}")
    
    print(f"\nTotal Engagement:")
    print(f"  Likes: {stats['total_engagement']['likes']}")
    print(f"  Comments: {stats['total_engagement']['comments']}")
    print(f"  Shares: {stats['total_engagement']['shares']}")
    
    print(f"\n{'='*60}")


def cmd_recent(args, manager: SocialSummaryManager):
    """Show recent posts."""
    posts = manager.get_recent_posts(
        limit=args.limit if hasattr(args, 'limit') else 10,
        platform=args.platform if hasattr(args, 'platform') else None
    )
    
    if not posts:
        print("\n[INFO] No posts found.")
        return
    
    print(f"\n{'='*60}")
    print(f"Recent Posts ({len(posts)} shown)")
    print(f"{'='*60}")
    
    for post in posts:
        print(f"\n[{post.get('date', 'Unknown')}] {post.get('platform', 'Unknown').title()}")
        print(f"  Status: {post.get('status', 'unknown').title()}")
        print(f"  Content: {post.get('content', '')[:100]}...")
        engagement = post.get('engagement', {})
        if engagement:
            print(f"  Engagement: {engagement.get('likes', 0)} likes, {engagement.get('comments', 0)} comments")
        if post.get('post_url'):
            print(f"  URL: {post.get('post_url')}")
    
    print(f"\n{'='*60}")


def cmd_export(args, manager: SocialSummaryManager):
    """Export social log."""
    activities = manager._load_activities()
    
    if args.format == 'json':
        output_file = manager.logs_dir / "social_export.json"
        with open(output_file, 'w') as f:
            json.dump(activities, f, indent=2, default=str)
        print(f"\n[OK] Exported {len(activities)} activities to: {output_file}")
    
    elif args.format == 'csv':
        import csv
        output_file = manager.reports_dir / "social_export.csv"
        with open(output_file, 'w', newline='', encoding='utf-8') as f:
            writer = csv.writer(f)
            writer.writerow(['Date', 'Platform', 'Content', 'Status', 'Likes', 'Comments', 'Shares', 'URL'])
            for post in activities:
                engagement = post.get('engagement', {})
                writer.writerow([
                    post.get('date', ''),
                    post.get('platform', ''),
                    post.get('content', '')[:100],
                    post.get('status', ''),
                    engagement.get('likes', ''),
                    engagement.get('comments', ''),
                    engagement.get('shares', ''),
                    post.get('post_url', '')
                ])
        print(f"\n[OK] Exported {len(activities)} activities to: {output_file}")


# ============================================================================
# Skill Entry Point
# ============================================================================

def social_summary_skill(platform: str, content: str, post_id: str = None,
                        post_url: str = None, status: str = "published",
                        engagement: Dict = None, tags: List[str] = None) -> Dict:
    """Main entry point for social-summary skill."""
    manager = SocialSummaryManager()
    return manager.log_post(
        platform=platform,
        content=content,
        post_id=post_id,
        post_url=post_url,
        status=status,
        engagement=engagement,
        tags=tags
    )


# ============================================================================
# Main Entry Point
# ============================================================================

def main():
    """Main entry point for CLI."""
    parser = argparse.ArgumentParser(
        description='Social Summary Skill - Track Social Media Activities',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog='''
Examples:
  Log LinkedIn post:
    python social_summary.py log --platform linkedin --content "Post text"
  
  Log with engagement:
    python social_summary.py log --platform linkedin --content "Post" --engagement '{"likes": 50, "comments": 10}'
  
  Log with tags:
    python social_summary.py log --platform linkedin --content "Post" --tags "#business,#innovation"
  
  Show summary:
    python social_summary.py summary --days 7
  
  Show recent posts:
    python social_summary.py recent --limit 10
  
  Export data:
    python social_summary.py export --format json
    python social_summary.py export --format csv
        '''
    )
    
    subparsers = parser.add_subparsers(dest='command', help='Available commands')
    
    # Log command
    log_parser = subparsers.add_parser('log', help='Log a social media post')
    log_parser.add_argument('--platform', '-p', required=True, help='Social media platform')
    log_parser.add_argument('--content', '-c', required=True, help='Post content')
    log_parser.add_argument('--post-id', help='Platform-specific post ID')
    log_parser.add_argument('--post-url', help='Direct URL to post')
    log_parser.add_argument('--status', default='published', choices=['published', 'scheduled', 'draft', 'failed'], help='Post status')
    log_parser.add_argument('--engagement', help='Engagement metrics as JSON')
    log_parser.add_argument('--tags', help='Comma-separated tags/hashtags')
    log_parser.set_defaults(func=cmd_log)
    
    # Summary command
    summary_parser = subparsers.add_parser('summary', help='Show social media summary')
    summary_parser.add_argument('--days', '-d', type=int, default=7, help='Number of days')
    summary_parser.add_argument('--platform', '-p', help='Filter by platform')
    summary_parser.set_defaults(func=cmd_summary)
    
    # Recent command
    recent_parser = subparsers.add_parser('recent', help='Show recent posts')
    recent_parser.add_argument('--limit', '-l', type=int, default=10, help='Number of posts')
    recent_parser.add_argument('--platform', '-p', help='Filter by platform')
    recent_parser.set_defaults(func=cmd_recent)
    
    # Export command
    export_parser = subparsers.add_parser('export', help='Export social log')
    export_parser.add_argument('--format', '-f', required=True, choices=['json', 'csv'], help='Export format')
    export_parser.set_defaults(func=cmd_export)
    
    # Parse arguments
    args = parser.parse_args()
    
    if not args.command:
        parser.print_help()
        sys.exit(0)
    
    # Create manager and execute command
    manager = SocialSummaryManager()
    args.func(args, manager)


if __name__ == '__main__':
    main()
